### ISSUE TITLE
Manager approves an Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#137]
**User story:**
As a manager who approves Activity Reports and sees some needing approval on my Home page, I want to be able to open the submitted report, read it, and approve it, so that I can do my part to help the TTA Specialist complete their work.

**Acceptance Criteria:**
- [x] in a submitted report assigned to a manager for review and approval, that manager can select an option to approve the report
- [x] an approved report's status changes to "Approved"

Design link: https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880478/simulate/sitemap

**Exclusions:**
- display of a list of approvers and each one's approval status #227 
- ability of managers to find reports that need their review, #191 
- workflow for manager-requested revisions, #138 
- display of approved reports, #5

**Comment by PatricePascual-ACF** [comment]
@pamlo412 - Just to flesh this out a bit more for design @arickalewis1: 
"- [ ] if there is more than one approving managers, the report remains in a "Pending Approval" status until all assigned managers have approved it" 

When a report has two approvers, there's a distincion between the "My Activity Report" view/status and the "Region (X) Activity Reports" status. 
Manager 1, who has approved the report, will not expect to see that report in their "My Activity..." list because their work is done.  
Manager 2, who still needs to approve the report, will need it to show up as "Needs Action" on their "My Activity..." list. 
The report status under "Region (X)..." can still show "Pending Approval."

**Comment by pamlo412** [comment]
@PatricePascual-ACF - your comment above affects the display on the Home page, so I'm adding your notes to #181
